# Generated by Django 3.0.6 on 2020-05-21 12:29

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('index', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('_id', models.CharField(max_length=128, unique=True)),
                ('guid', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('age', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('has_died', models.BooleanField(default=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=32)),
                ('picture', models.CharField(blank=True, max_length=256, null=True)),
                ('eye_color', models.CharField(blank=True, max_length=32, null=True)),
                ('gender', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.CharField(blank=True, max_length=32, null=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('registered', models.DateTimeField(blank=True, null=True)),
                ('greeting', models.TextField(blank=True, null=True)),
                ('friend', django_mysql.models.ListTextField(models.IntegerField(), size=100)),
                ('tags', django_mysql.models.ListTextField(models.CharField(max_length=32), size=100)),
                ('fruits', django_mysql.models.ListTextField(models.CharField(max_length=32), size=100)),
                ('vegetables', django_mysql.models.ListTextField(models.CharField(max_length=32), size=100)),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.Companies')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_index', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_friend', to='citizen.Citizen')),
                ('people_index', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_person', to='citizen.Citizen')),
            ],
        ),
        migrations.AddField(
            model_name='citizen',
            name='myfriends',
            field=models.ManyToManyField(blank=True, related_name='_citizen_myfriends_+', through='citizen.Friend', to='citizen.Citizen'),
        ),
    ]
