# Generated by Django 3.0.6 on 2020-05-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('index', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('company', models.CharField(max_length=100)),
            ],
        ),
    ]
